http_utility: removed unused using
GCC 15.1 fails with the following:

```
19:18:43 | ../git/include/http_utility.hpp:50:30: error: unused using-declaration 'boost::spirit::x3::uint_' [-Werror=unused-variable]
19:18:43 |    50 |     using boost::spirit::x3::uint_;
```

Fix it with a trivial removal of an unused using.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ia24038d3146e818062dfb3f6c0c6bc84fa1ba470